### ISSUE TITLE
I can not download Robo-VLN Dataset.

### ISSUE THREAD

**Issue by yyf17** [GT-RIPL/robo-vln#2]
![image](https://user-images.githubusercontent.com/34536352/121130452-010dda00-c861-11eb-9a43-79e6c8099167.png)
I download from url(https://www.dropbox.com/s/dl/1e339avr84tfrbt/robo_vln_v1.zip), but failed.
will you help me ?
Thanks.

**Comment by zubair-irshad** [comment]
@yyf17 I would try downloading the data again using the link provided. Based on the recent commit, https://github.com/GT-RIPL/robo-vln/commit/b16b0d3e109a1ddd8edba9359cda4fc2221d3cc1, the correct access rights have been granted for the dataset.

**Comment by yyf17** [comment]
@zubair-irshad Thank you. I successfully downloaded the dataset.
