### ISSUE TITLE
lmdb.Error

### ISSUE THREAD

**Issue by yyf17** [GT-RIPL/robo-vln#3]
Thank you for your very interesting research and sharing code. I encountered the following error when I run the command "python run.py --exp-config robo_vln_baselines/config/paper_configs/robovln_data_train.yaml --run-type train":
![image](https://user-images.githubusercontent.com/34536352/122677128-93c05880-d213-11eb-847c-eeca3ef05dae.png)
Then I went to check the storage directory of the trajectory data and found that the data has reached 2T, as shown below:
data/trajectories_dirs/robo-vln/train/trajectories.lmdb
![image](https://user-images.githubusercontent.com/34536352/122677607-9fad1a00-d215-11eb-8cc8-4664714fb0c1.png)
Finally, I checked the hard disk and found that the hard disk still had free space.
![image](https://user-images.githubusercontent.com/34536352/122677540-4cd36280-d215-11eb-9111-0ac1c8417de2.png)
Please tell me what should I do, thank you.

**Comment by zubair-irshad** [comment]
@yyf17 This does seem like a disk space error i.e. you might be running out of diskspace. Please see this [thread](https://stackoverflow.com/questions/47683601/how-to-resolve-lmdb-error-mdb-txn-commit-input-output-error).  

The other thing you could try is to increase the `LMDB_MAP_SIZE` [here](https://github.com/GT-RIPL/robo-vln/blob/master/robo_vln_baselines/config/default.py#L65). Although the current `LMDB_MAP_SIZE` i.e. 2.7e12 was sufficient to collect all the data on our end. 

You can also start training with the current collected data (i.e. 7642 trajectories), however, we recommend collecting the complete data to reproduce our [paper results](https://github.com/GT-RIPL/robo-vln#modelsresults-from-the-paper).

**Comment by yyf17** [comment]
@zubair-irshad Thank you for your patience and guidance. I doubled the` LMDB_MAP_SIZE=5.4e12`, hoping to collect the trajectory successfully.

**Comment by zubair-irshad** [comment]
No worries. I am closing this issue now. If you ever run into the error again, please feel free to re-open the issue and I would be happy to look into it again.

**Comment by yyf17** [comment]
@zubair-irshad Thank you for your patient guidance. The same error occurred, but I still failed to collect 7739 data. The specific screenshots are as follows:
![image](https://user-images.githubusercontent.com/34536352/122852574-738fb700-d343-11eb-9206-bf9ec501cd8f.png)
The hard disk space of the machine is sure to be sufficient. The configuration of my machine looks like this:
![image](https://user-images.githubusercontent.com/34536352/122852819-d5e8b780-d343-11eb-8236-692d927c2d03.png)
I don't know what went wrong.

**Comment by yyf17** [comment]
@zubair-irshad 
The scene where the error occurred occurred while capturing the trajectory of the` mp3d/E9uDoFAP3SH` scene.
![image](https://user-images.githubusercontent.com/34536352/122853884-80150f00-d345-11eb-80ed-ada51bd015a7.png)

**Comment by zubair-irshad** [comment]
@yyf17 This error indicates either of the two problems i.e. 1. `LMDB_MAP_SIZE` is too small (I see that you have already increased it to a better range so we can rule this one out. 2. you might be running out of diskspace. 

I would recommend looking at your diskspace or changing the machine to see if the error persists.

**Comment by yyf17** [comment]
@zubair-irshad 
Thank you for your excellent work and patient guidance. This problem is solved: it is caused by my newly added hard disk format: Ext3 only supports files up to 2T. I changed it to EXt4 and solved the problem.
![image](https://user-images.githubusercontent.com/34536352/123227272-0298fc80-d507-11eb-9336-f81a1e3ae00e.png)

**Comment by zubair-irshad** [comment]
@yyf17 Great to hear this!
