### ISSUE TITLE
no trainer for Random Agent Error.

### ISSUE THREAD

**Issue by yyf17** [GT-RIPL/robo-vln#4]
@zubair-irshad 
Thank you for your very interesting research and sharing code.
When I run the cmd as following:
```
CUDA_VISIBLE_DEVICES=0,1 python run.py --exp-config robo_vln_baselines/config/nonlearning.yaml --run-type train
```
I encountered the following error:
![image](https://user-images.githubusercontent.com/34536352/123232202-81903400-d50b-11eb-838c-6adcc43dca17.png)

**Comment by zubair-irshad** [comment]
Please see latest commit: https://github.com/GT-RIPL/robo-vln/commit/286870a7d1095fe2607b524572587a48854bc970
