### ISSUE TITLE
I couldn't download ddppo's  pretained network,will you help me

### ISSUE THREAD

**Issue by Moon-heart** [GT-RIPL/robo-vln#7]

**Comment by Moon-heart** [comment]
I followed the path points (https://github.com/facebookresearch/habitat-lab/tree/master/habitat_baselines/rl/ddppo(url) found that the file could not found. 

will you help me?
thanks

**Comment by zubair-irshad** [comment]
Apologies, the previous link might have broken. Here is the link for the ddppo weights: `https://github.com/facebookresearch/habitat-lab/tree/v0.1.7/habitat_baselines/rl/ddppo#pretrained-models-pointgoal-navigation-with-gpscompass`

The direct download link (taken from above) is as follows: https://dl.fbaipublicfiles.com/habitat/data/baselines/v1/ddppo/ddppo-models.zip

**Comment by Moon-heart** [comment]
Now it can be downloaded normally. Thank you very much foy your reply.
